<a href="https://colab.research.google.com/github/monalipawar23/ML-lab/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

Prepare Data set (hr strudy )

In [ ]:
X = np.array([[1], [2], [2.5], [2.9], [3.7], [5], [5.6], [5.9], [6], [8], [4.9], [10]])

In [ ]:
print(type(X))

<class 'numpy.ndarray'>


Pass = 1 , Fail = 0

In [ ]:
y = np.array([0,0,0,0,1,1,1,1,1,1,1,1])

Train test split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state = 11)

In [ ]:
X_train

array([[ 4.9],
       [ 2.5],
       [10. ],
       [ 3.7],
       [ 5. ],
       [ 5.9],
       [ 2. ],
       [ 1. ],
       [ 8. ]])

In [ ]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 0, 1])

In [ ]:
X_test

array([[5.6],
       [2.9],
       [6. ]])

In [ ]:
y_test

array([1, 0, 1])

In [ ]:

from sklearn.linear_model import LogisticRegression

m = LogisticRegression()

In [ ]:
m.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred =m.predict(X_test)
print(y_pred)

[1 0 1]


In [ ]:
a = accuracy_score(y_pred,y_test)
print(a)

1.0


In [ ]:
hours = np.array ([[6]])

In [ ]:
output= m.predict(hours)

In [ ]:
print(output)

[1]


In [ ]:
print("probability of fail",prob[0],[0])
print("Probability of pass",prob[1],[1]) bh

NameError: name 'prob' is not defined